services:
    _defaults:
        bind:
            $projectDir: '%kernel.project_dir%'
#    DoctrineCiphersweetBundle\Command\:
#        resource: '../../Command/*'
#        autowire: true
#        tags:
#            - { name: 'console.command' }

