services:
    DoctrineCiphersweetBundle\Subscribers\DoctrineCiphersweetSubscriber:
        class: DoctrineCiphersweetBundle\Subscribers\DoctrineCiphersweetSubscriber
        arguments: ["@annotation_reader", "@DoctrineCiphersweetBundle\\Encryptors\\CiphersweetEncryptor", "%doctrine_ciphersweet.keys%"]
        tags:
            -  { name: doctrine.event_subscriber }

    DoctrineCiphersweetBundle\Encryptors\CiphersweetEncryptor:
        class: DoctrineCiphersweetBundle\Encryptors\CiphersweetEncryptor
        arguments:
            - "%doctrine_ciphersweet.keys%"